In [122]:
import pandas as pd

In [123]:
test = pd.read_csv("us-county-boundaries.csv", engine="pyarrow", sep=";")

In [124]:
illinois = test[test["STATEFP"]==17]
illinois.index = pd.Index(range(0, len(illinois)))

In [125]:
illinois['FIPS'] = [(str(int(illinois["STATEFP"][i])//10)+str(int(illinois["STATEFP"][i])%10)+str(int(illinois["COUNTYFP"][i])//100)+str(int(illinois["COUNTYFP"][i])//10%10)+str(int(illinois["COUNTYFP"][i])%10)) for i in range(0, len(illinois))]
illinois

/tmp/ipykernel_59372/3347915558.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  illinois['FIPS'] = [(str(int(illinois["STATEFP"][i])//10)+str(int(illinois["STATEFP"][i])%10)+str(int(illinois["COUNTYFP"][i])//100)+str(int(illinois["COUNTYFP"][i])//10%10)+str(int(illinois["COUNTYFP"][i])%10)) for i in range(0, len(illinois))]

,Geo Point,Geo Shape,STATEFP,COUNTYFP,COUNTYNS,GEOID,NAME,NAMELSAD,STUSAB,LSAD,...,CBSAFP,METDIVFP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,STATE_NAME,COUNTYFP NOZERO,FIPS
0,"39.0855054887, -90.3565282985","{""coordinates"": [[[-90.592165, 39.086765], [-9...",17,83,424243,17083,Jersey,Jersey County,IL,6,...,41180.0,NaN,A,957415147,20333975,+39.0801945,-090.3613850,Illinois,83,17083
1,"41.4041459264, -89.5286557577","{""coordinates"": [[[-89.856913, 41.408836], [-8...",17,11,424207,17011,Bureau,Bureau County,IL,6,...,36837.0,NaN,A,2250935503,11472955,+41.4013043,-089.5283772,Illinois,11,17011
2,"41.2044899818, -89.2857803179","{""coordinates"": [[[-89.333027, 41.132961], [-8...",17,155,424279,17155,Putnam,Putnam County,IL,6,...,36837.0,NaN,A,414649309,31195045,+41.1989613,-089.2983474,Illinois,155,17155
3,"40.2396222297, -89.9168137955","{""coordinates"": [[[-90.114921, 40.245482], [-9...",17,125,424261,17125,Mason,Mason County,IL,6,...,NaN,NaN,A,1396914851,62748513,+40.2369926,-089.9135746,Illinois,125,17125
4,"42.0425663561, -89.3207266558","{""coordinates"": [[[-89.685984, 42.112009], [-8...",17,141,1784894,17141,Ogle,Ogle County,IL,6,...,40300.0,NaN,A,1964903717,12378959,+42.0418840,-089.3201764,Illinois,141,17141
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,"39.0001785652, -89.0241202321","{""coordinates"": [[[-89.250603, 39.152012], [-8...",17,51,424227,17051,Fayette,Fayette County,IL,6,...,NaN,NaN,A,1855567160,22931323,+39.0011246,-089.0179232,Illinois,51,17051
98,"41.3440027805, -88.8859379256","{""coordinates"": [[[-89.166473, 41.541697], [-8...",17,99,422247,17099,LaSalle,LaSalle County,IL,6,...,36837.0,NaN,A,2940070811,33698037,+41.3433407,-088.8859312,Illinois,99,17099
99,"40.7880635936, -89.7599800409","{""coordinates"": [[[-89.985333, 40.800074], [-8...",17,143,1784920,17143,Peoria,Peoria County,IL,6,...,37900.0,NaN,A,1602464183,30659935,+40.7859722,-089.7669933,Illinois,143,17143
100,"40.4037747348, -91.1646955496","{""coordinates"": [[[-91.374208, 40.463993], [-9...",17,67,424235,17067,Hancock,Hancock County,IL,6,...,22800.0,NaN,A,2055798692,53563370,+40.4013180,-091.1688008,Illinois,67,17067
101,"40.4908916187, -88.847324278","{""coordinates"": [[[-89.266499, 40.485552], [-8...",17,113,1784833,17113,McLean,McLean County,IL,6,...,14010.0,NaN,A,3064600918,7801224,+40.4945594,-088.8445391,Illinois,113,17113

In [126]:
test2 = pd.read_csv("racial.csv")
test2

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,ESTIMATESBASE2020,POPESTIMATE2020,POPESTIMATE2021,...,RESIDUAL2021,GQESTIMATESBASE2020,GQESTIMATES2020,GQESTIMATES2021,RBIRTH2021,RDEATH2021,RNATURALCHG2021,RINTERNATIONALMIG2021,RDOMESTICMIG2021,RNETMIG2021
0,40,3,6,1,0,Alabama,Alabama,5024279,5024803,5039877,...,242,114572,114572,114572,11.191613,12.890226,-1.698613,0.247201,4.398749,4.645950
1,50,3,6,1,1,Alabama,Autauga County,58805,58877,59095,...,8,442,442,442,11.002611,11.545112,-0.542502,0.084766,4.017903,4.102668
2,50,3,6,1,3,Alabama,Baldwin County,231767,233140,239294,...,-82,2177,2177,2177,9.567474,12.137145,-2.569671,0.266704,28.702422,28.969126
3,50,3,6,1,5,Alabama,Barbour County,25223,25180,24964,...,1,2789,2789,2789,10.928526,15.714742,-4.786216,0.039885,-3.908743,-3.868858
4,50,3,6,1,7,Alabama,Bibb County,22293,22223,22477,...,-1,2062,2062,2062,10.111857,12.617450,-2.505593,0.089485,13.825503,13.914989
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3189,50,4,8,56,37,Wyoming,Sweetwater County,42272,42158,41614,...,-4,720,720,720,11.483551,9.549730,1.933820,0.429738,-15.255694,-14.825956
3190,50,4,8,56,39,Wyoming,Teton County,23331,23347,23575,...,1,215,215,215,9.377264,4.091897,5.285367,0.340991,4.049273,4.390265
3191,50,4,8,56,41,Wyoming,Uinta County,20450,20441,20635,...,0,187,187,187,11.003993,8.082579,2.921414,0.146071,6.378420,6.524491
3192,50,4,8,56,43,Wyoming,Washakie County,7685,7658,7705,...,-1,119,119,119,9.893901,14.971034,-5.077133,0.000000,11.325913,11.325913
3193,50,4,8,56,45,Wyoming,Weston County,6838,6809,6745,...,1,300,300,300,7.673012,13.280212,-5.607201,0.000000,-3.984064,-3.984064

In [127]:
illinois_data = test2[test2["STNAME"]=="Illinois"]
illinois_data.index = pd.Index(range(0,len(illinois_data)))

In [131]:
illinois["NAME"]

0       Jersey
1       Bureau
2       Putnam
3        Mason
4         Ogle
        ...
97     Fayette
98     LaSalle
99      Peoria
100    Hancock
101     McLean
Name: NAME, Length: 102, dtype: object

In [132]:
superfund = pd.read_excel("superfund_sites.xlsx")
superfund

,EPA ID,Site Name,City,County,State,Street Address,Zip Code,Region,NPL Status,Partial NPL Deletion,...,Site Type Subcategory,Federal Agency,Native American Interest (NAI),Indian Entity (NAI Status),HRS Score,Federal Facility Indicator,Alias/Alternative Site Name,Non-NPL Status Date,Superfund Site Profile Page URL,RCRA Handler ID - RCRA Handler Name
0,NED981713837,10TH STREET SITE,COLUMBUS,PLATTE,NE,28TH AVE & 10TH ST,68601,R07,Final NPL,No,...,Ground water plume site with no identifiable s...,NaN,No,NaN,28.90,No,"10TH STREET SITE, COLUMBUS PUBLIC WATER SUPPLY...",02/13/1987,www.epa.gov/superfund/10thstreet,NaN
1,KSD007241656,29TH & MEAD GROUND WATER CONTAMINATION,WICHITA,SEDGWICK,KS,412 E 29TH N 26S 1E SW 1/4 S 33,67219,R07,Deleted NPL,Yes,...,Ground water plume site with no identifiable s...,NaN,No,NaN,NaN,No,"29TH & MEAD GROUND WATER CONTAMINATION, 29TH &...",01/01/1996,www.epa.gov/superfund/29thandmead,NaN
2,ALN000410750,35TH AVENUE,BIRMINGHAM,JEFFERSON,AL,3500 35TH N.,35207,R04,Proposed NPL,No,...,"Coal gasification, Residential, Spill or other...",NaN,No,NaN,50.00,No,"35TH AVENUE COKE SITE, 35TH AVENUE SITE, WALTE...",09/22/2014,www.epa.gov/superfund/35th-avenue,NaN
3,KSD981710247,57TH AND NORTH BROADWAY STREETS SITE,WICHITA,SEDGWICK,KS,57TH & N BROADWAY STREETS,67219,R07,Final NPL,No,...,Ground water plume site with no identifiable s...,NaN,No,NaN,50.00,No,"57TH AND N. BROADWAY STREETS SITE, 57TH AND NO...",02/04/1987,www.epa.gov/superfund/57thandbroadway,NaN
4,MDD980918387,68TH STREET DUMP/INDUSTRIAL ENTERPRISES,ROSEDALE,BALTIMORE,MD,68TH STREET,21237,R03,Proposed NPL,No,...,Co-disposal landfill (municipal and industrial...,NaN,No,NaN,50.00,No,"68TH STREET DUMP, 68TH STREET DUMP/INDUSTRIAL ...",04/30/2003,www.epa.gov/superfund/68thstreet,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1892,NYD000511733,YORK OIL CO.,MOIRA,FRANKLIN,NY,N LAWRENCE RD,12957,R02,Final NPL,No,...,Waste/used oil,NaN,No,NaN,47.70,No,"PEIRCE DUMP, YORK OIL CO, YORK OIL CO., YORK O...",09/01/1980,www.epa.gov/superfund/york-oil,NaN
1893,AZ0971590062,YUMA MARINE CORPS AIR STATION,YUMA,YUMA,AZ,AVENUE 3E,85369,R09,Final NPL,No,...,Trucks/ships/trains/aircraft and related compo...,Department of Defense,No,NaN,32.24,Yes,"MARINE CORPS AIR STA, YUMA, MARINE CORPS AIR S...",[Blank Date],www.epa.gov/superfund/yumausmc,NaN
1894,OHD980794598,ZANESVILLE WELL FIELD,ZANESVILLE,MUSKINGUM,OH,2200 LINDEN,43701,R05,Final NPL,No,...,Ground water plume site with no identifiable s...,NaN,No,NaN,35.59,No,"ZANESVILLE WELL FIELD, ZANESVILLE WELL FIELD",06/01/1982,www.epa.gov/superfund/zanesville-wellfield,NaN
1895,FLD049985302,ZELLWOOD GROUND WATER CONTAMINATION,ZELLWOOD,ORANGE,FL,803 JONES AVE,32757,R04,Final NPL,No,...,Drums/tanks,NaN,No,NaN,51.91,No,"DRUM SVC CO OF FL, ZELLWOOD GROUND WATER CONTA...",[Blank Date],www.epa.gov/superfund/zellwood-groundwater-con...,NaN
1896,NJD986643153,ZSCHIEGNER REFINING,HOWELL TOWNSHIP,MONMOUTH,NJ,1442 MAXIM-SOUTHARD ROAD,7731,R02,Final NPL,No,...,Batteries/scrap metals/secondary smelting/prec...,NaN,No,NaN,50.00,No,"ZSCHIEGNER REFINING, ZSCHIEGNER REFINING",03/11/1994,www.epa.gov/superfund/zschiegner-refining,NaN

In [51]:

sites = superfund[superfund["State"]=="IL"]
sites.index = pd.Index(range(0, len(sites)))

In [133]:
sites["County"] = [sites['County'][i].capitalize() for i in range(len(sites))]

/tmp/ipykernel_59372/4057664734.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sites["County"] = [sites['County'][i].capitalize() for i in range(len(sites))]

In [135]:
test3 = [illinois[sites["County"][i]==illinois["NAME"]] for i in range(len(sites))]
test3 = [test3[i].iloc[:, :2] for i in range(len(test3))]
test3

[                        Geo Point  \
 56  39.2733468255, -88.2401981662

                                             Geo Shape
 56  {"coordinates": [[[-88.471139, 39.272968], [-8...  ,
                         Geo Point  \
 60  42.3362603021, -89.1608658488

                                             Geo Shape
 60  {"coordinates": [[[-89.398011, 42.375173], [-8...  ,
                         Geo Point  \
 50  41.8954290221, -87.6461407931

                                             Geo Shape
 50  {"coordinates": [[[-88.238186, 42.066985], [-8...  ,
                         Geo Point  \
 57  39.9879052609, -91.1884921409

                                             Geo Shape
 57  {"coordinates": [[[-91.424108, 39.93575], [-91...  ,
 Empty DataFrame
 Columns: [Geo Point, Geo Shape]
 Index: [],
                        Geo Point  \
 7  41.4450504457, -87.9786458597

                                            Geo Shape
 7  {"coordinates": [[[-88.255348, 41.550089], [-8...  ,
                         Geo Point  \
 47  39.2310459341, -89.4788485523

                                             Geo Shape
 47  {"coordinates": [[[-89.700396, 39.435828], [-8...  ,
 Empty DataFrame
 Columns: [Geo Point, Geo Shape]
 Index: [],
                         Geo Point  \
 60  42.3362603021, -89.1608658488

                                             Geo Shape
 60  {"coordinates": [[[-89.398011, 42.375173], [-8...  ,
                         Geo Point  \
 77  42.3230756866, -88.8233754157

                                             Geo Shape
 77  {"coordinates": [[[-88.940753, 42.41387], [-88...  ,
                        Geo Point  \
 4  42.0425663561, -89.3207266558

                                            Geo Shape
 4  {"coordinates": [[[-89.685984, 42.112009], [-8...  ,
                         Geo Point  \
 35  39.5458317531, -89.2772543125

                                             Geo Shape
 35  {"coordinates": [[[-89.255282, 39.814716], [-8...  ,
                       Geo Point  \
 85  38.8297122608, -89.90499843

                                             Geo Shape
 85  {"coordinates": [[[-90.110007, 38.833548], [-9...  ,
                         Geo Point  \
 17  38.6064621876, -89.4224823889

                                             Geo Shape
 17  {"coordinates": [[[-89.705605, 38.567913], [-8...  ,
                         Geo Point  \
 75  41.1377184724, -87.8618317846

                                             Geo Shape
 75  {"coordinates": [[[-87.664806, 41.296823], [-8...  ,
                        Geo Point  \
 1  41.4041459264, -89.5286557577

                                            Geo Shape
 1  {"coordinates": [[[-89.856913, 41.408836], [-8...  ,
 Empty DataFrame
 Columns: [Geo Point, Geo Shape]
 Index: [],
                         Geo Point  \
 47  39.2310459341, -89.4788485523

                                             Geo Shape
 47  {"coordinates": [[[-89.700396, 39.435828], [-8...  ,
 Empty DataFrame
 Columns: [Geo Point, Geo Shape]
 Index: [],
                         Geo Point  \
 50  41.8954290221, -87.6461407931

                                             Geo Shape
 50  {"coordinates": [[[-88.238186, 42.066985], [-8...  ,
                         Geo Point  \
 60  42.3362603021, -89.1608658488

                                             Geo Shape
 60  {"coordinates": [[[-89.398011, 42.375173], [-8...  ,
                         Geo Point  \
 53  40.9318279821, -90.2132382621

                                             Geo Shape
 53  {"coordinates": [[[-90.440524, 40.97649], [-90...  ,
                       Geo Point  \
 6  42.325322722, -87.6311845438

                                            Geo Shape
 6  {"coordinates": [[[-88.198601, 42.415567], [-8...  ,
                       Geo Point  \
 73  40.183401621, -87.732815214

                                             Geo Shape
 73  {"coordinates": [[[-87.929442, 40.269693], [-8...  ,
                        Geo Point  \
 91  37.191593361, -89.3376041231

                                             Geo Shape
 91  {"coordinates": [[[-89.199751, 37.088868], [-8...  ,
                         Geo Point  \
 45  38.7199480156, -87.7267298383

                                             Geo Shape
 45  {"coordinates": [[[-87.759592, 38.849514], [-8...  ,
                         Geo Point  \
 60  42.3362603021, -89.1608658488

                                             Geo Shape
 60  {"coordinates": [[[-89.398011, 42.375173], [-8...  ,
                       Geo Point  \
 85  38.8297122608, -89.90499843

                                             Geo Shape
 85  {"coordinates": [[[-90.110007, 38.833548], [-9...  ,
                       Geo Point  \
 6  42.325322722, -87.6311845438

                                            Geo Shape
 6  {"coordinates": [[[-88.198601, 42.415567], [-8...  ,
                        Geo Point  \
 7  41.4450504457, -87.9786458597

                                            Geo Shape
 7  {"coordinates": [[[-88.255348, 41.550089], [-8...  ,
                        Geo Point  \
 7  41.4450504457, -87.9786458597

                                            Geo Shape
 7  {"coordinates": [[[-88.255348, 41.550089], [-8...  ,
 Empty DataFrame
 Columns: [Geo Point, Geo Shape]
 Index: [],
 Empty DataFrame
 Columns: [Geo Point, Geo Shape]
 Index: [],
 Empty DataFrame
 Columns: [Geo Point, Geo Shape]
 Index: [],
 Empty DataFrame
 Columns: [Geo Point, Geo Shape]
 Index: [],
                         Geo Point  \
 50  41.8954290221, -87.6461407931

                                             Geo Shape
 50  {"coordinates": [[[-88.238186, 42.066985], [-8...  ,
 Empty DataFrame
 Columns: [Geo Point, Geo Shape]
 Index: [],
 Empty DataFrame
 Columns: [Geo Point, Geo Shape]
 Index: [],
 Empty DataFrame
 Columns: [Geo Point, Geo Shape]
 Index: [],
                         Geo Point  \
 77  42.3230756866, -88.8233754157

                                             Geo Shape
 77  {"coordinates": [[[-88.940753, 42.41387], [-88...  ,
                       Geo Point  \
 85  38.8297122608, -89.90499843

                                             Geo Shape
 85  {"coordinates": [[[-90.110007, 38.833548], [-9...  ,
                       Geo Point  \
 6  42.325322722, -87.6311845438

                                            Geo Shape
 6  {"coordinates": [[[-88.198601, 42.415567], [-8...  ,
                       Geo Point  \
 6  42.325322722, -87.6311845438

                                            Geo Shape
 6  {"coordinates": [[[-88.198601, 42.415567], [-8...  ,
 Empty DataFrame
 Columns: [Geo Point, Geo Shape]
 Index: [],
 Empty DataFrame
 Columns: [Geo Point, Geo Shape]
 Index: [],
 Empty DataFrame
 Columns: [Geo Point, Geo Shape]
 Index: [],
                       Geo Point  \
 6  42.325322722, -87.6311845438

                                            Geo Shape
 6  {"coordinates": [[[-88.198601, 42.415567], [-8...  ,
                         Geo Point  \
 60  42.3362603021, -89.1608658488

                                             Geo Shape
 60  {"coordinates": [[[-89.398011, 42.375173], [-8...  ,
                         Geo Point  \
 77  42.3230756866, -88.8233754157

                                             Geo Shape
 77  {"coordinates": [[[-88.940753, 42.41387], [-88...  ,
                         Geo Point  \
 50  41.8954290221, -87.6461407931

                                             Geo Shape
 50  {"coordinates": [[[-88.238186, 42.066985], [-8...  ,
                         Geo Point  \
 50  41.8954290221, -87.6461407931

                                             Geo Shape
 50  {"coordinates": [[[-88.238186, 42.066985], [-8...  ,
                         Geo Point  \
 50  41.8954290221, -87.6461407931

                                             Geo Shape
 50  {"coordinates": [[[-88.238186, 42.066985], [-8...  ,
                         Geo Point  \
 50  41.8954290221, -87.6461407931

                                             Geo Shape
 50  {"coordinates": [[[-88.238186, 42.066985], [-8...  ,
                         Geo Point  \
 50  41.8954290221, -87.6461407931

                                             Geo Shape
 50  {"coordinates": [[[-88.238186, 42.066985], [-8...  ,
                         Geo Point  \
 50  41.8954290221, -87.6461407931

                                             Geo Shape
 50  {"coordinates": [[[-88.238186, 42.066985], [-8...  ,
                         Geo Point  \
 50  41.8954290221, -87.6461407931

                                             Geo Shape
 50  {"coordinates": [[[-88.238186, 42.066985], [-8...  ,
                         Geo Point  \
 50  41.8954290221, -87.6461407931

                                             Geo Shape
 50  {"coordinates": [[[-88.238186, 42.066985], [-8...  ,
                       Geo Point  \
 6  42.325322722, -87.6311845438

                                            Geo Shape
 6  {"coordinates": [[[-88.198601, 42.415567], [-8...  ,
                         Geo Point  \
 52  38.6495781117, -88.9189811153

                                             Geo Shape
 52  {"coordinates": [[[-88.807644, 38.82446], [-88...  ,
                         Geo Point  \
 13  37.7302529228, -88.9299244512

                                             Geo Shape
 13  {"coordinates": [[[-89.151677, 37.773956], [-8...  ,
 Empty DataFrame
 Columns: [Geo Point, Geo Shape]
 Index: [],
 Empty DataFrame
 Columns: [Geo Point, Geo Shape]
 Index: [],
 Empty DataFrame
 Columns: [Geo Point, Geo Shape]
 Index: [],
                         Geo Point  \
 50  41.8954290221, -87.6461407931

                                             Geo Shape
 50  {"coordinates": [[[-88.238186, 42.066985], [-8...  ,
                         Geo Point  \
 60  42.3362603021, -89.1608658488

                                             Geo Shape
 60  {"coordinates": [[[-89.398011, 42.375173], [-8...  ,
                         Geo Point  \
 40  41.9388566679, -88.4286377038

                                             Geo Shape
 40  {"coordinates": [[[-88.601289, 41.981473], [-8...  ,
                         Geo Point  \
 86  39.3335754723, -87.7877174066

                                             Geo Shape
 86  {"coordinates": [[[-88.011728, 39.349837], [-8...  ,
                       Geo Point  \
 6  42.325322722, -87.6311845438

                                            Geo Shape
 6  {"coordinates": [[[-88.198601, 42.415567], [-8...  ,
 Empty DataFrame
 Columns: [Geo Point, Geo Shape]
 Index: [],
                       Geo Point  \
 6  42.325322722, -87.6311845438

                                            Geo Shape
 6  {"coordinates": [[[-88.198601, 42.415567], [-8...  ]

In [139]:
illinois.iloc[:, [0,1,3]]

,Geo Point,Geo Shape,COUNTYFP
0,"39.0855054887, -90.3565282985","{""coordinates"": [[[-90.592165, 39.086765], [-9...",83
1,"41.4041459264, -89.5286557577","{""coordinates"": [[[-89.856913, 41.408836], [-8...",11
2,"41.2044899818, -89.2857803179","{""coordinates"": [[[-89.333027, 41.132961], [-8...",155
3,"40.2396222297, -89.9168137955","{""coordinates"": [[[-90.114921, 40.245482], [-9...",125
4,"42.0425663561, -89.3207266558","{""coordinates"": [[[-89.685984, 42.112009], [-8...",141
...,...,...,...
97,"39.0001785652, -89.0241202321","{""coordinates"": [[[-89.250603, 39.152012], [-8...",51
98,"41.3440027805, -88.8859379256","{""coordinates"": [[[-89.166473, 41.541697], [-8...",99
99,"40.7880635936, -89.7599800409","{""coordinates"": [[[-89.985333, 40.800074], [-8...",143
100,"40.4037747348, -91.1646955496","{""coordinates"": [[[-91.374208, 40.463993], [-9...",67
101,"40.4908916187, -88.847324278","{""coordinates"": [[[-89.266499, 40.485552], [-8...",113

In [143]:
illinois = illinois.sort_values(by=['COUNTYFP'])
illinois.index = pd.Index(range(len(illinois)))
illinois

,Geo Point,Geo Shape,STATEFP,COUNTYFP,COUNTYNS,GEOID,NAME,NAMELSAD,STUSAB,LSAD,...,CBSAFP,METDIVFP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,STATE_NAME,COUNTYFP NOZERO,FIPS
0,"39.9879052609, -91.1884921409","{""coordinates"": [[[-91.424108, 39.93575], [-91...",17,1,424202,17001,Adams,Adams County,IL,6,...,39500.0,NaN,A,2214804481,41776031,+39.9860525,-091.1949607,Illinois,1,17001
1,"37.191593361, -89.3376041231","{""coordinates"": [[[-89.199751, 37.088868], [-8...",17,3,424203,17003,Alexander,Alexander County,IL,6,...,16020.0,NaN,A,609667772,44539209,+37.1836583,-089.3495158,Illinois,3,17003
2,"38.8868296401, -89.4355442381","{""coordinates"": [[[-89.361793, 39.027724], [-8...",17,5,424204,17005,Bond,Bond County,IL,6,...,41180.0,NaN,A,985073265,6462629,+38.8859240,-089.4365916,Illinois,5,17005
3,"42.3230756866, -88.8233754157","{""coordinates"": [[[-88.940753, 42.41387], [-88...",17,7,424205,17007,Boone,Boone County,IL,6,...,40420.0,NaN,A,727180620,3363818,+42.3189831,-088.8242951,Illinois,7,17007
4,"39.9617616288, -90.7503556212","{""coordinates"": [[[-90.914687, 40.018039], [-9...",17,9,424206,17009,Brown,Brown County,IL,6,...,NaN,NaN,A,791828628,4144346,+39.9620694,-090.7503095,Illinois,9,17009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,"41.7562548803, -89.9141029918","{""coordinates"": [[[-90.181788, 41.843538], [-9...",17,195,1785167,17195,Whiteside,Whiteside County,IL,6,...,44580.0,NaN,A,1771808919,31883752,+41.7506733,-089.9110045,Illinois,195,17195
98,"41.4450504457, -87.9786458597","{""coordinates"": [[[-88.255348, 41.550089], [-8...",17,197,1785190,17197,Will,Will County,IL,6,...,16980.0,16984.0,A,2164895527,34582450,+41.4484742,-087.9784564,Illinois,197,17197
99,"37.7302529228, -88.9299244512","{""coordinates"": [[[-89.151677, 37.773956], [-8...",17,199,1785215,17199,Williamson,Williamson County,IL,6,...,16060.0,NaN,A,1088349246,62460141,+37.7303533,-088.9300182,Illinois,199,17199
100,"42.3362603021, -89.1608658488","{""coordinates"": [[[-89.398011, 42.375173], [-8...",17,201,1785216,17201,Winnebago,Winnebago County,IL,6,...,40420.0,NaN,A,1329068433,15598347,+42.3373957,-089.1612053,Illinois,201,17201
101,"40.7882358798, -89.2111061648","{""coordinates"": [[[-89.047718, 40.925749], [-8...",17,203,1785231,17203,Woodford,Woodford County,IL,6,...,37900.0,NaN,A,1366821840,38477370,+40.7897870,-089.2105871,Illinois,203,17203

In [144]:
set(sites["County"])

{'Adams',
 'Alexander',
 'Boone',
 'Bureau',
 'Christian',
 'Clark',
 'Clinton',
 'Cook',
 'Cumberland',
 'Dupage',
 'Jo daviess',
 'Kane',
 'Kankakee',
 'Knox',
 'La salle',
 'Lake',
 'Lawrence',
 'Madison',
 'Marion',
 'Mchenry',
 'Montgomery',
 'Ogle',
 'St. clair',
 'Vermilion',
 'Will',
 'Williamson',
 'Winnebago'}

In [96]:
sites.to_csv("illinois_sites.csv")

In [113]:
test4 = pd.read_csv("racial.csv")
test4 = test4[test4["COUNTY"] != 0]
test4.index = pd.Index(range(len(test4)))

In [114]:
test4['FIPS'] = [(str(int(test4["STATE"][i])//10)+str(int(test4["STATE"][i])%10)+str(int(test4["COUNTY"][i])//100)+str(int(test4["COUNTY"][i])//10%10)+str(int(test4["COUNTY"][i])%10)) for i in range(0, len(test4))]

In [116]:
test4.to_csv("racial_fips3.csv")

In [115]:
test4

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,ESTIMATESBASE2020,POPESTIMATE2020,POPESTIMATE2021,...,GQESTIMATESBASE2020,GQESTIMATES2020,GQESTIMATES2021,RBIRTH2021,RDEATH2021,RNATURALCHG2021,RINTERNATIONALMIG2021,RDOMESTICMIG2021,RNETMIG2021,FIPS
0,50,3,6,1,1,Alabama,Autauga County,58805,58877,59095,...,442,442,442,11.002611,11.545112,-0.542502,0.084766,4.017903,4.102668,01001
1,50,3,6,1,3,Alabama,Baldwin County,231767,233140,239294,...,2177,2177,2177,9.567474,12.137145,-2.569671,0.266704,28.702422,28.969126,01003
2,50,3,6,1,5,Alabama,Barbour County,25223,25180,24964,...,2789,2789,2789,10.928526,15.714742,-4.786216,0.039885,-3.908743,-3.868858,01005
3,50,3,6,1,7,Alabama,Bibb County,22293,22223,22477,...,2062,2062,2062,10.111857,12.617450,-2.505593,0.089485,13.825503,13.914989,01007
4,50,3,6,1,9,Alabama,Blount County,59134,59081,59041,...,449,449,449,10.650006,13.883950,-3.233945,0.033863,2.370431,2.404294,01009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3138,50,4,8,56,37,Wyoming,Sweetwater County,42272,42158,41614,...,720,720,720,11.483551,9.549730,1.933820,0.429738,-15.255694,-14.825956,56037
3139,50,4,8,56,39,Wyoming,Teton County,23331,23347,23575,...,215,215,215,9.377264,4.091897,5.285367,0.340991,4.049273,4.390265,56039
3140,50,4,8,56,41,Wyoming,Uinta County,20450,20441,20635,...,187,187,187,11.003993,8.082579,2.921414,0.146071,6.378420,6.524491,56041
3141,50,4,8,56,43,Wyoming,Washakie County,7685,7658,7705,...,119,119,119,9.893901,14.971034,-5.077133,0.000000,11.325913,11.325913,56043
3142,50,4,8,56,45,Wyoming,Weston County,6838,6809,6745,...,300,300,300,7.673012,13.280212,-5.607201,0.000000,-3.984064,-3.984064,56045

In [121]:
test["Geo Shape"]

0       {"coordinates": [[[-98.273667, 40.089399], [-9...
1       {"coordinates": [[[-84.397189, 40.786584], [-8...
2       {"coordinates": [[[-81.488643, 41.631522], [-8...
3       {"coordinates": [[[-94.617088, 37.477776], [-9...
4       {"coordinates": [[[-85.561745, 44.952258], [-8...
                              ...
3228    {"coordinates": [[[-82.455197, 38.844579], [-8...
3229    {"coordinates": [[[-85.415774, 31.490413], [-8...
3230    {"coordinates": [[[-94.612713, 38.313115], [-9...
3231    {"coordinates": [[[-90.093625, 32.707628], [-9...
3232    {"coordinates": [[[-101.692269, 32.271062], [-...
Name: Geo Shape, Length: 3233, dtype: object

In [247]:
races = pd.read_excel("illinois_racial.xlsx",header=None).T
races

,0,1,2,3,4,5,6,7,8,9,...,62,63,64,65,66,67,68,69,70,71
0,Label,Total:,Population of one race:,White alone,Black or African American alone,American Indian and Alaska Native alone,Asian alone,Native Hawaiian and Other Pacific Islander alone,Some Other Race alone,Population of two or more races:,...,American Indian and Alaska Native; Asian; Nati...,Population of five races:,White; Black or African American; American Ind...,White; Black or African American; American Ind...,White; Black or African American; American Ind...,White; Black or African American; Asian; Nativ...,White; American Indian and Alaska Native; Asia...,Black or African American; American Indian and...,Population of six races:,White; Black or African American; American Ind...
1,"Adams County, Illinois","65,737","62,520","58,837","2,501",104,513,39,526,"3,217",...,0,0,0,0,0,0,0,0,0,0
2,"Alexander County, Illinois","5,240","4,978","3,311","1,617",24,6,0,20,262,...,0,0,0,0,0,0,0,0,0,0
3,"Bond County, Illinois","16,725","16,051","14,446","1,077",52,105,11,360,674,...,0,0,0,0,0,0,0,0,0,0
4,"Boone County, Illinois","53,448","47,368","38,766","1,245",498,659,24,"6,176","6,080",...,0,4,4,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,"Whiteside County, Illinois","55,691","51,290","47,759",839,235,311,12,"2,134","4,401",...,0,0,0,0,0,0,0,0,0,0
99,"Will County, Illinois","696,355","625,921","443,562","80,979","3,974","42,849",126,"54,431","70,434",...,0,11,4,7,0,0,0,0,4,4
100,"Williamson County, Illinois","67,153","63,369","58,897","2,870",263,776,9,554,"3,784",...,0,0,0,0,0,0,0,0,4,4
101,"Winnebago County, Illinois","285,350","259,097","191,124","39,159","1,632","8,039",84,"19,059","26,253",...,0,6,0,0,0,6,0,0,2,2
102,"Woodford County, Illinois","38,467","36,872","36,102",278,49,217,14,212,"1,595",...,0,3,2,1,0,0,0,0,0,0

In [248]:
races.columns = races.iloc[0]
races = races.drop(0)

In [250]:
races = races.rename(columns={"Total:":"Total Pop", "White alone":"White Pop","Label":"County"})
races.index = pd.Index(range(len(races)))
races

,County,Total Pop,Population of one race:,White Pop,Black or African American alone,American Indian and Alaska Native alone,Asian alone,Native Hawaiian and Other Pacific Islander alone,Some Other Race alone,Population of two or more races:,...,American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race,Population of five races:,White; Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander,White; Black or African American; American Indian and Alaska Native; Asian; Some Other Race,White; Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some Other Race,White; Black or African American; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race,White; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race,Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race,Population of six races:,White; Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race
0,"Adams County, Illinois","65,737","62,520","58,837","2,501",104,513,39,526,"3,217",...,0,0,0,0,0,0,0,0,0,0
1,"Alexander County, Illinois","5,240","4,978","3,311","1,617",24,6,0,20,262,...,0,0,0,0,0,0,0,0,0,0
2,"Bond County, Illinois","16,725","16,051","14,446","1,077",52,105,11,360,674,...,0,0,0,0,0,0,0,0,0,0
3,"Boone County, Illinois","53,448","47,368","38,766","1,245",498,659,24,"6,176","6,080",...,0,4,4,0,0,0,0,0,0,0
4,"Brown County, Illinois","6,244","6,066","4,779","1,054",11,12,0,210,178,...,0,1,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,"Whiteside County, Illinois","55,691","51,290","47,759",839,235,311,12,"2,134","4,401",...,0,0,0,0,0,0,0,0,0,0
98,"Will County, Illinois","696,355","625,921","443,562","80,979","3,974","42,849",126,"54,431","70,434",...,0,11,4,7,0,0,0,0,4,4
99,"Williamson County, Illinois","67,153","63,369","58,897","2,870",263,776,9,554,"3,784",...,0,0,0,0,0,0,0,0,4,4
100,"Winnebago County, Illinois","285,350","259,097","191,124","39,159","1,632","8,039",84,"19,059","26,253",...,0,6,0,0,0,6,0,0,2,2
101,"Woodford County, Illinois","38,467","36,872","36,102",278,49,217,14,212,"1,595",...,0,3,2,1,0,0,0,0,0,0

In [252]:
races["County"] = [races["County"][i][:-10] for i in range(len(races))]

In [254]:
races["County"][1]

'Alexander County'

In [266]:
races["Total Pop"] = [int(races["Total Pop"][i].replace(",","")) for i in range(len(races))]
races["White Pop"] = [int(races["White Pop"][i].replace(",","")) for i in range(len(races))]
races["Black or African American alone"] = [int(races["Black or African American alone"][i].replace(",","")) for i in range(len(races))]

In [267]:
races["Percent Not White"] = pd.Series((races["Total Pop"]-races["White Pop"])/races["Total Pop"]*100//1, name="Percent Not White")
races["Percent Black"] = pd.Series((races["Black or African American alone"])/races["Total Pop"]*100//1, name="Percent Not White")

In [217]:
test5 = races[["County", "Percent Not White"]]

In [270]:
illinois["Percent Not White"] = races["Percent Not White"]
illinois["Percent Black"] = races["Percent Black"]

In [271]:
illinois[["FIPS","NAMELSAD", "Percent Not White", "Percent Black"]].to_csv("percents_fips.csv")

In [272]:
illinois

,Geo Point,Geo Shape,STATEFP,COUNTYFP,COUNTYNS,GEOID,NAME,NAMELSAD,STUSAB,LSAD,...,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,STATE_NAME,COUNTYFP NOZERO,FIPS,Percent Not White,Percent Black
0,"39.9879052609, -91.1884921409","{""coordinates"": [[[-91.424108, 39.93575], [-91...",17,1,424202,17001,Adams,Adams County,IL,6,...,A,2214804481,41776031,+39.9860525,-091.1949607,Illinois,1,17001,10.0,3.0
1,"37.191593361, -89.3376041231","{""coordinates"": [[[-89.199751, 37.088868], [-8...",17,3,424203,17003,Alexander,Alexander County,IL,6,...,A,609667772,44539209,+37.1836583,-089.3495158,Illinois,3,17003,36.0,30.0
2,"38.8868296401, -89.4355442381","{""coordinates"": [[[-89.361793, 39.027724], [-8...",17,5,424204,17005,Bond,Bond County,IL,6,...,A,985073265,6462629,+38.8859240,-089.4365916,Illinois,5,17005,13.0,6.0
3,"42.3230756866, -88.8233754157","{""coordinates"": [[[-88.940753, 42.41387], [-88...",17,7,424205,17007,Boone,Boone County,IL,6,...,A,727180620,3363818,+42.3189831,-088.8242951,Illinois,7,17007,27.0,2.0
4,"39.9617616288, -90.7503556212","{""coordinates"": [[[-90.914687, 40.018039], [-9...",17,9,424206,17009,Brown,Brown County,IL,6,...,A,791828628,4144346,+39.9620694,-090.7503095,Illinois,9,17009,23.0,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,"41.7562548803, -89.9141029918","{""coordinates"": [[[-90.181788, 41.843538], [-9...",17,195,1785167,17195,Whiteside,Whiteside County,IL,6,...,A,1771808919,31883752,+41.7506733,-089.9110045,Illinois,195,17195,14.0,1.0
98,"41.4450504457, -87.9786458597","{""coordinates"": [[[-88.255348, 41.550089], [-8...",17,197,1785190,17197,Will,Will County,IL,6,...,A,2164895527,34582450,+41.4484742,-087.9784564,Illinois,197,17197,36.0,11.0
99,"37.7302529228, -88.9299244512","{""coordinates"": [[[-89.151677, 37.773956], [-8...",17,199,1785215,17199,Williamson,Williamson County,IL,6,...,A,1088349246,62460141,+37.7303533,-088.9300182,Illinois,199,17199,12.0,4.0
100,"42.3362603021, -89.1608658488","{""coordinates"": [[[-89.398011, 42.375173], [-8...",17,201,1785216,17201,Winnebago,Winnebago County,IL,6,...,A,1329068433,15598347,+42.3373957,-089.1612053,Illinois,201,17201,33.0,13.0
101,"40.7882358798, -89.2111061648","{""coordinates"": [[[-89.047718, 40.925749], [-8...",17,203,1785231,17203,Woodford,Woodford County,IL,6,...,A,1366821840,38477370,+40.7897870,-089.2105871,Illinois,203,17203,6.0,0.0

In [268]:
races

,County,Total Pop,Population of one race:,White Pop,Black or African American alone,American Indian and Alaska Native alone,Asian alone,Native Hawaiian and Other Pacific Islander alone,Some Other Race alone,Population of two or more races:,...,White; Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander,White; Black or African American; American Indian and Alaska Native; Asian; Some Other Race,White; Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some Other Race,White; Black or African American; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race,White; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race,Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race,Population of six races:,White; Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race,Percent Not White,Percent Black
0,Adams County,65737,"62,520",58837,2501,104,513,39,526,"3,217",...,0,0,0,0,0,0,0,0,10.0,3.0
1,Alexander County,5240,"4,978",3311,1617,24,6,0,20,262,...,0,0,0,0,0,0,0,0,36.0,30.0
2,Bond County,16725,"16,051",14446,1077,52,105,11,360,674,...,0,0,0,0,0,0,0,0,13.0,6.0
3,Boone County,53448,"47,368",38766,1245,498,659,24,"6,176","6,080",...,4,0,0,0,0,0,0,0,27.0,2.0
4,Brown County,6244,"6,066",4779,1054,11,12,0,210,178,...,0,0,1,0,0,0,0,0,23.0,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,Whiteside County,55691,"51,290",47759,839,235,311,12,"2,134","4,401",...,0,0,0,0,0,0,0,0,14.0,1.0
98,Will County,696355,"625,921",443562,80979,"3,974","42,849",126,"54,431","70,434",...,4,7,0,0,0,0,4,4,36.0,11.0
99,Williamson County,67153,"63,369",58897,2870,263,776,9,554,"3,784",...,0,0,0,0,0,0,4,4,12.0,4.0
100,Winnebago County,285350,"259,097",191124,39159,"1,632","8,039",84,"19,059","26,253",...,0,0,0,6,0,0,2,2,33.0,13.0
101,Woodford County,38467,"36,872",36102,278,49,217,14,212,"1,595",...,2,1,0,0,0,0,0,0,6.0,0.0

In [280]:
with_sites = set(sites.County)

In [286]:
with_sites = {site:0 for site in with_sites}

In [287]:
with_sites

{'Marion': 0,
 'La salle': 0,
 'Alexander': 0,
 'Dupage': 0,
 'Mchenry': 0,
 'Bureau': 0,
 'Madison': 0,
 'Cumberland': 0,
 'Kankakee': 0,
 'Jo daviess': 0,
 'Ogle': 0,
 'Boone': 0,
 'Christian': 0,
 'Knox': 0,
 'St. clair': 0,
 'Williamson': 0,
 'Cook': 0,
 'Lawrence': 0,
 'Clark': 0,
 'Adams': 0,
 'Montgomery': 0,
 'Clinton': 0,
 'Vermilion': 0,
 'Kane': 0,
 'Winnebago': 0,
 'Will': 0,
 'Lake': 0}

In [288]:
for i in range(len(sites)):
    try:
        with_sites[sites["County"][i]] += 1
    except:
        continue

In [292]:
with_sites = {site+" County":with_sites[site] for site in with_sites}

In [293]:
with_sites

{'Marion County': 1,
 'La salle County': 4,
 'Alexander County': 1,
 'Dupage County': 7,
 'Mchenry County': 1,
 'Bureau County': 1,
 'Madison County': 3,
 'Cumberland County': 1,
 'Kankakee County': 1,
 'Jo daviess County': 2,
 'Ogle County': 1,
 'Boone County': 3,
 'Christian County': 1,
 'Knox County': 1,
 'St. clair County': 4,
 'Williamson County': 1,
 'Cook County': 12,
 'Lawrence County': 1,
 'Clark County': 1,
 'Adams County': 1,
 'Montgomery County': 2,
 'Clinton County': 1,
 'Vermilion County': 1,
 'Kane County': 1,
 'Winnebago County': 6,
 'Will County': 3,
 'Lake County': 8}

In [303]:
illinois["Superfund Sites"] = [0 for i in range(len(illinois))]
for i in range(len(illinois)):
    try:
        illinois["Superfund Sites"][i] = with_sites[illinois["NAMELSAD"][i]]
    except:
        continue

/tmp/ipykernel_59372/1610699587.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  illinois["Superfund Sites"][i] = with_sites[illinois["NAMELSAD"][i]]
/tmp/ipykernel_59372/1610699587.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  illinois["Superfund Sites"][i] = with_sites[illinois["NAMELSAD"][i]]
/tmp/ipykernel_59372/1610699587.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  illinois["Superfund Sites"][i] = with_sites[illinois["NAMELSAD"][i]]
/tmp/ipykernel_59372/1610699587.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  illinois["Superfund Sites"][i] = with_sites[illinois["NAMELSAD"][i]]
/tmp/ipykernel_59372/1610699587.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  illinois["Superfund Sites"][i] = with_sites[illinois["NAMELSAD"][i]]
/tmp/ipykernel_59372/1610699587.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  illinois["Superfund Sites"][i] = with_sites[illinois["NAMELSAD"][i]]
/tmp/ipykernel_59372/1610699587.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  illinois["Superfund Sites"][i] = with_sites[illinois["NAMELSAD"][i]]
/tmp/ipykernel_59372/1610699587.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  illinois["Superfund Sites"][i] = with_sites[illinois["NAMELSAD"][i]]
/tmp/ipykernel_59372/1610699587.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  illinois["Superfund Sites"][i] = with_sites[illinois["NAMELSAD"][i]]
/tmp/ipykernel_59372/1610699587.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  illinois["Superfund Sites"][i] = with_sites[illinois["NAMELSAD"][i]]
/tmp/ipykernel_59372/1610699587.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  illinois["Superfund Sites"][i] = with_sites[illinois["NAMELSAD"][i]]
/tmp/ipykernel_59372/1610699587.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  illinois["Superfund Sites"][i] = with_sites[illinois["NAMELSAD"][i]]
/tmp/ipykernel_59372/1610699587.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  illinois["Superfund Sites"][i] = with_sites[illinois["NAMELSAD"][i]]
/tmp/ipykernel_59372/1610699587.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  illinois["Superfund Sites"][i] = with_sites[illinois["NAMELSAD"][i]]
/tmp/ipykernel_59372/1610699587.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  illinois["Superfund Sites"][i] = with_sites[illinois["NAMELSAD"][i]]
/tmp/ipykernel_59372/1610699587.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  illinois["Superfund Sites"][i] = with_sites[illinois["NAMELSAD"][i]]
/tmp/ipykernel_59372/1610699587.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  illinois["Superfund Sites"][i] = with_sites[illinois["NAMELSAD"][i]]
/tmp/ipykernel_59372/1610699587.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  illinois["Superfund Sites"][i] = with_sites[illinois["NAMELSAD"][i]]
/tmp/ipykernel_59372/1610699587.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  illinois["Superfund Sites"][i] = with_sites[illinois["NAMELSAD"][i]]
/tmp/ipykernel_59372/1610699587.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  illinois["Superfund Sites"][i] = with_sites[illinois["NAMELSAD"][i]]
/tmp/ipykernel_59372/1610699587.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  illinois["Superfund Sites"][i] = with_sites[illinois["NAMELSAD"][i]]
/tmp/ipykernel_59372/1610699587.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  illinois["Superfund Sites"][i] = with_sites[illinois["NAMELSAD"][i]]

In [305]:
illinois[["FIPS","NAMELSAD", "Superfund Sites"]].to_csv("sites_fips.csv")

In [309]:
incomes = pd.read_excel("decennial_income_data.xlsx")
incomes

,Unnamed: 0,"Adams County, Illinois",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 1014,Unnamed: 1015,Unnamed: 1016,Unnamed: 1017,Unnamed: 1018,Unnamed: 1019,Unnamed: 1020,Unnamed: 1021,Unnamed: 1022,Unnamed: 1023
0,NaN,Total population,NaN,White alone,NaN,White alone or in combination with one or more...,NaN,Black or African American alone,NaN,Black or African American alone or in combinat...,...,NaN,Guatemalan (222),NaN,Honduran (223),NaN,Nicaraguan (224),NaN,Panamanian (225),NaN,Salvadoran (226)
1,Label,Number,Percent,Number,Percent,Number,Percent,Number,Percent,Number,...,Percent,Number,Percent,Number,Percent,Number,Percent,Number,Percent,Number
2,EMPLOYMENT STATUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Population 16 years and over,"53,348",100.0,"51,098",100.0,"51,463",100.0,"1,419",100.0,"1,508",...,100.0,"13,643",100.0,"3,030",100.0,918,100.0,"1,002",100.0,"3,942"
4,In labor force,"35,122",65.8,"33,688",65.9,"33,930",65.9,846,59.6,898,...,71.1,"8,455",62.0,"2,063",68.1,649,70.7,749,74.8,"2,729"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,Percent below poverty level,(X),12.0,(X),10.4,(X),10.8,(X),34.4,(X),...,42.8,(X),16.6,(X),15.8,(X),20.8,(X),5.9,(X)
113,Related children 5 to 17 years,"1,379",(X),"1,176",(X),"1,225",(X),119,(X),162,...,(X),458,(X),80,(X),21,(X),12,(X),211
114,Percent below poverty level,(X),11.0,(X),10.0,(X),10.3,(X),24.8,(X),...,27.1,(X),15.9,(X),11.9,(X),12.1,(X),5.1,(X)
115,Unrelated individuals 15 years and over,"2,387",(X),"2,221",(X),"2,254",(X),108,(X),121,...,(X),517,(X),187,(X),79,(X),19,(X),275
116,Percent below poverty level,(X),21.7,(X),21.1,(X),21.3,(X),33.3,(X),...,29.9,(X),30.2,(X),35.1,(X),42.0,(X),7.0,(X)

In [317]:
for i in range(0, len(incomes.iloc[0])):
    try:
        incomes.pop("Unnamed: "+str(i))
    except:
        continue

In [316]:
incomes = incomes.rename(columns={"Unnamed: 0": "Labels"})
incomes

,Labels,"Adams County, Illinois",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 1014,Unnamed: 1015,Unnamed: 1016,Unnamed: 1017,Unnamed: 1018,Unnamed: 1019,Unnamed: 1020,Unnamed: 1021,Unnamed: 1022,Unnamed: 1023
0,NaN,Total population,NaN,White alone,NaN,White alone or in combination with one or more...,NaN,Black or African American alone,NaN,Black or African American alone or in combinat...,...,NaN,Guatemalan (222),NaN,Honduran (223),NaN,Nicaraguan (224),NaN,Panamanian (225),NaN,Salvadoran (226)
1,Label,Number,Percent,Number,Percent,Number,Percent,Number,Percent,Number,...,Percent,Number,Percent,Number,Percent,Number,Percent,Number,Percent,Number
2,EMPLOYMENT STATUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Population 16 years and over,"53,348",100.0,"51,098",100.0,"51,463",100.0,"1,419",100.0,"1,508",...,100.0,"13,643",100.0,"3,030",100.0,918,100.0,"1,002",100.0,"3,942"
4,In labor force,"35,122",65.8,"33,688",65.9,"33,930",65.9,846,59.6,898,...,71.1,"8,455",62.0,"2,063",68.1,649,70.7,749,74.8,"2,729"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,Percent below poverty level,(X),12.0,(X),10.4,(X),10.8,(X),34.4,(X),...,42.8,(X),16.6,(X),15.8,(X),20.8,(X),5.9,(X)
113,Related children 5 to 17 years,"1,379",(X),"1,176",(X),"1,225",(X),119,(X),162,...,(X),458,(X),80,(X),21,(X),12,(X),211
114,Percent below poverty level,(X),11.0,(X),10.0,(X),10.3,(X),24.8,(X),...,27.1,(X),15.9,(X),11.9,(X),12.1,(X),5.1,(X)
115,Unrelated individuals 15 years and over,"2,387",(X),"2,221",(X),"2,254",(X),108,(X),121,...,(X),517,(X),187,(X),79,(X),19,(X),275
116,Percent below poverty level,(X),21.7,(X),21.1,(X),21.3,(X),33.3,(X),...,29.9,(X),30.2,(X),35.1,(X),42.0,(X),7.0,(X)

In [320]:
incomes["Adams County, Illinois"]

0      Total population
1                Number
2                   NaN
3                53,348
4                35,122
             ...
112                 (X)
113               1,379
114                 (X)
115               2,387
116                 (X)
Name: Adams County, Illinois, Length: 117, dtype: object

In [321]:
for name in incomes.columns:
    print(name)

Labels
Adams County, Illinois
Alexander County, Illinois
Bond County, Illinois
Boone County, Illinois
Brown County, Illinois
Bureau County, Illinois
Calhoun County, Illinois
Carroll County, Illinois
Cass County, Illinois
Champaign County, Illinois
Christian County, Illinois
Clark County, Illinois
Clay County, Illinois
Clinton County, Illinois
Coles County, Illinois
Cook County, Illinois